ALTER TABLE "AspNetUsers" ADD COLUMN IF NOT EXISTS "EstActif" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "OffresEmploi" ADD COLUMN IF NOT EXISTS "Competences" TEXT;
ALTER TABLE "OffresEmploi" ADD COLUMN IF NOT EXISTS "Icon" TEXT;
ALTER TABLE "OffresEmploi" ADD COLUMN IF NOT EXISTS "IconColor" TEXT;
ALTER TABLE "Entreprises" ADD COLUMN IF NOT EXISTS "Taille" TEXT;
ALTER TABLE "Entreprises" ADD COLUMN IF NOT EXISTS "Ville" TEXT;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260226220748_AddEntrepriseFields', '10.0.3') ON CONFLICT DO NOTHING;
