// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222120341_FinalIdentityStructure")]
    partial class FinalIdentityStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatePostulation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .HasColumnType("text");

                    b.Property<int>("OffreEmploiId")
                        .HasColumnType("integer");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("OffreEmploiId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("Backend.Models.OffreEmploi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("ExperienceRequise")
                        .HasColumnType("text");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModeDeTravail")
                        .HasColumnType("text");

                    b.Property<int>("NbPost")
                        .HasColumnType("integer");

                    b.Property<float?>("Salaire")
                        .HasColumnType("real");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDeContact")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("OffresEmploi");
                });

            modelBuilder.Entity("Backend.Models.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chronometre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateEvaluation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NiveauDifficulte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OffreEmploiId")
                        .HasColumnType("integer");

                    b.Property<string>("Reponses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OffreEmploiId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Backend.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.Admin", b =>
                {
                    b.HasBaseType("Backend.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Backend.Models.Candidat", b =>
                {
                    b.HasBaseType("Backend.Models.Utilisateur");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Candidat");
                });

            modelBuilder.Entity("Backend.Models.Entreprise", b =>
                {
                    b.HasBaseType("Backend.Models.Utilisateur");

                    b.Property<string>("Secteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Entreprise");
                });

            modelBuilder.Entity("Backend.Models.Candidature", b =>
                {
                    b.HasOne("Backend.Models.Candidat", "Candidat")
                        .WithMany("Candidatures")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.OffreEmploi", "OffreEmploi")
                        .WithMany("Candidatures")
                        .HasForeignKey("OffreEmploiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("OffreEmploi");
                });

            modelBuilder.Entity("Backend.Models.OffreEmploi", b =>
                {
                    b.HasOne("Backend.Models.Entreprise", "Entreprise")
                        .WithMany("Offres")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Backend.Models.Questions", b =>
                {
                    b.HasOne("Backend.Models.OffreEmploi", "OffreEmploi")
                        .WithMany("Questions")
                        .HasForeignKey("OffreEmploiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OffreEmploi");
                });

            modelBuilder.Entity("Backend.Models.OffreEmploi", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Backend.Models.Candidat", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("Backend.Models.Entreprise", b =>
                {
                    b.Navigation("Offres");
                });
#pragma warning restore 612, 618
        }
    }
}
